package com.yongle.goku.system.mapper;

import com.yongle.goku.model.system.SysOrgUser;
import com.yongle.goku.model.system.SysOrgUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    long countByExample(SysOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int deleteByExample(SysOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orgId") Long orgId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int insert(SysOrgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int insertSelective(SysOrgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    List<SysOrgUser> selectByExample(SysOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysOrgUser record, @Param("example") SysOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysOrgUser record, @Param("example") SysOrgUserExample example);
}